name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        env:
          CI: true
        run: |
          npm install
      - name: npm install claudia and tsc
        env:
          CI: true
        run: |
          npm install -g claudia tsc
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      - name: Add Exisiting Sam Config
        run: |
          if [ -n "${{ vars.SAMCONFIG }}" ]; then
          echo "${{ vars.SAMCONFIG }}" > samconfig.toml
          else
            echo "Error: SAMCONFIG variable not set or is empty"
            exit 1
          fi
      - name: Build project
        run: |
          npm run build
      - name: Generate lambda files
        run: |
          npm run lambda:build
        env:
          SAM_CLI_TELEMETRY: 0
      - name: Deploying to lambda
        run: |
          npm run lambda:deploy
