name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY}}"
      AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_KEY}}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: npm install claudia and tsc
        env:
          CI: true
        run: |
          npm install -g claudia tsc
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Adding aws access key
        run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY}}" >> .env
      - name: Adding aws secret key
        run: |
          echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_KEY}}" >> .env
      - name: Build project
        run: |
          npm run build
      - name: Generate lambda files
        run: |
          npm run lambda:generate
      - name: Deploying to lambda
        run: |
          npm run lambda:deploy

